### PR TITLE
chore: Use crawler

### PR DESCRIPTION
**Pull request by stefanomunarini**

### CODE REVIEW

**Comment by CAMOBAP** [comment]
@stefanomunarini I just tested on relaton's repo. I think only `Gemfile` should be enough for this case (without `Gemfile.lock`)

https://github.com/relaton/relaton-data-rfcs/pull/4

**Comment by CAMOBAP** [comment]
@stefanomunarini I just updated reusable workflow now it should correctly handle this case, could you please re-run workflow

**Comment by stefanomunarini** [comment]
I do not seem to have permissions to re run the workflow, and perhaps it has been disabled cause even pushing a new commit, won't trigger the workflow @CAMOBAP . Perhaps @kesara can re-run the workflow? Thanks

**Comment by stefanomunarini** [comment]
@CAMOBAP are we still overriding both the Gemfile and the Gemfile.lock ? Or only Gemfile?

**Comment by CAMOBAP** [comment]
> I do not seem to have permissions to re run the workflow, and perhaps it has been disabled cause even pushing a new commit, won't trigger the workflow @CAMOBAP . Perhaps @kesara can re-run the workflow? Thanks

You can push some changes to rerun it, but first, you have to resolve flag.txt conflict

**Comment by stefanomunarini** [comment]
> @stefanomunarini I just updated reusable workflow now it should correctly handle this case, could you please re-run workflow

Thank you @CAMOBAP . Workflow now runs successfully.

@kesara I do not have permissions to assign PRs in ietf-tools organization, can I simply mention you in the comments? Thanks

**Comment by kesara** [comment]
> > @stefanomunarini I just updated reusable workflow now it should correctly handle this case, could you please re-run workflow
> 
> Thank you @CAMOBAP . Workflow now runs successfully.
> 
> @kesara I do not have permissions to assign PRs in ietf-tools organization, can I simply mention you in the comments? Thanks

Yeah, that's fine. You can also set PRs to drafts and change them ready to review when ready. Thanks.

**Review by kesara — APPROVED** [review]

**Pull request merged**
